{% set version = "1.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mi
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mi_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mi/mi_{{ version }}.tar.gz
  sha256: 4d7a9790dbdc675605d70755af9aa80c21a279be5a5d712b22d77465772cc785

build:
  noarch: generic
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-arm >=1.4_11
  run:
    - r-base
    - r-matrix
    - r-arm >=1.4_11

test:
  commands:
    - $R -e "library('mi')"           # [not win]
    - "\"%R%\" -e \"library('mi')\""  # [win]

about:
  home: http://www.stat.columbia.edu/~gelman/
  license: GPL-2.0-or-later
  summary: The mi package provides functions for data manipulation, imputing missing values in an approximate Bayesian framework, diagnostics of the models used to generate the imputations, confidence-building mechanisms to validate some of the assumptions of the imputation algorithm, and functions to analyze multiply imputed
    data sets with the appropriate degree of sampling uncertainty.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
