travis:
  secure:
    BINSTAR_TOKEN: rp+Gq+MGlGAVx2NaamvEyQQAqqkfKjl/O4zSNyc1tPqjaiiRh3n/y5MrO0Kv/H119FxDn9dA3DPzOTj8wqflGisucCnau0ogF5Ent6bwBG5hv/W10R21b/DDs/sZzoPW7KddWh85r0j/nP6C6dTXmZsMyYnpLz691JsyscCfPp2G7rY8Mb0R+252BFxhDRGf0AZmXGh36PJmZlelBLapsIc8BIc1iNWDXGvgnQICRscOL974+6yrz7knc4IHFhyqMhsNptKGm7VATIOIB483YXRmsqgB4b82Wdhs8yF1eD1oB5JuqyGPomAlGCGdQU85MLzfrTgZ46fnOccOCmiFdRMAGVqEYEryntY+clkcrNSrQzJ7p+r4ZQI2mpOngi6l/2DDh4g/rKdLsQHl7Vpsc8mCCy/be5qI8c5Wvj0nLUr/6j76TI55OtIQJQWM8PdIXbInpiL9Eznbu6ooNvQouVp4Kk59ZrxUbRjGh6fbDQqsO1WKgSU+aWuFz6bqwLeWm/gg5vEEZgn1PY1myk5gja/AMOZXtWSN4wtvLOn67FKEq5F5J8b/UXuFqk0mIwOilQDpNRhuzImj0VRUSkNO6ygoxu0F3135EH9GlSLXdvBpKCvz0k8hOhwhp3YToiIhnBGRxsAOotkuvEIVYYIYA1NMEl+gsD/RboFP4t2f+mc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
