appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: mxzfaAJ469gPpbwgYdRKcvtvCesqev6U7yx8dU1vbKKGQLKw6nDQBFz4x51NIBdrZt23eFnQNq1s/oFljIg27L0cHXw4PSsI3qsvlrXStBbC6gRdNdQ7q0g2HAlxZFpHlMHS+Ynbnt5ludzwlMBiqcfesHHqnVxsUfNiRZv5HdWevqB2cW5Y71VfbE9ygMAeJbM+SCGlFQMH2D2bR3M7m0ktRL4lD9JD36E3XfpKfWq/TIqwFxlDGOb+A6v3Isqk9H1BkCYZjVGlyB1fq9NmmFsx0woiQJyNouJvSIJDc2G24Vtfphqirt5qYG3U5p7OtSX0Wua1HZZ54Ys4hg7BncmD5ctI6U/10R7GLcMI4tGbN8kQXsuYRMdwVNFNC6xbijtFRPl4C2SVh1QIjQHugdJea+vDjO8cyzEf0PdAufUewzFdqy0TuVr5PdDHwpAT9likKdefrsmRN0jy7zxAoxOkLcCbywsOSDEI7ZA7c5wKsLVS74EWb6gNicWXFv/GQXfso1NzQr+OiKv6mbqVKy3lVj5uCZwOZ9SEAyw4GQRbnzyXxs9u3G2JIqgZdZu2wh2CMSxvy2l1lr4fcyFW95LusynAv00V0rj9vA62/LhtAtqMTKxdrIfmX48gKPo7u5bvCBuE9qAPPyt0sQGY4ksoGBL/yQz36iMeJfIwv4g=}
